### ISSUE TITLE
Dependency not available

### ISSUE THREAD

**Issue by hakkurishian** [flowkey/UIKit-cross-platform#258]
## Current behavior
When initializing the submodules the following error appears.

clone of 'git@github.com:flowkey/SDL2-SwiftPackageManager.git' into submodule path '/Users/huck/Desktop/UIKit-cross-platform/SDL' failed

## Expected behavior
Repository SDL2-SwiftPackagaManger.git to download correctly. Is it published? I cannot find it on GitHub.

## Steps to reproduce
1. Clone Repository
2. cd into directory
3. ``git submodule update --init --recursive`

**Comment by nerdmed** [comment]
@hakkurishian sorry about this, this should be resolved now! Would be great to hear if it works now for you!

Cheers

**Comment by hakkurishian** [comment]
thank you it works now 👍
