### ISSUE TITLE
`Error: Please select Android SDK` when running a UIKit project in Android Studio.

### ISSUE THREAD

**Issue by janekszynal** [flowkey/UIKit-cross-platform#260]
Tested on the Demo App from _/samples/getting-started_ as well as an existing iOS project that imported UIKit.

## Current behavior
When opened in Android Studio, the project doesn't run, reporting `Error: Please select Android SDK` (see screenshot below). This seems to be a fairly common problem in Android Studio, but common solutions I tried from StackOverflow didn't work.

## Expected behavior
The sample project should build and run smoothly.

## Steps to reproduce
1. Follow the readme instructions for adding UIKit or use the Demo App
2. Open the ./android folder of your UIKit project in Android Studio (install Android SDKs if necessary) and press "run" button

## Workaround
This problem can be avoided by following these steps:
1. Close project in Android Studio
2. Open another project or create a new one, in order to have access to the relevant menu option
3. Choose *File -> New -> Import project...* and import the UIKit project you want to run

Once that's done, the project runs fine, but doing *Build -> Refresh linked C++ projects* will 'break' it again and the workaround will have to be repeated.

## Screenshots
![screen shot 2018-07-23 at 14 25 08](https://user-images.githubusercontent.com/2146927/43105602-c4d001a2-8ed5-11e8-8cd8-dd5509f47e0f.png)

## Environment
- Device: MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
- OS: macOS 10.13.5 
- UIKit Version:

**Comment by ephemer** [comment]
Hi @janekszynal, just reposting a bit of what we wrote in Slack regarding this. Hopefully we can get to the bottom of it.

We also had issues with “Please select Android SDK” in testing, but were able to fix it by returning to a clean state of the UIKit repo with `git clean -xdf`.

Another thing to note is that there is a difference between dragging the `./android` folder onto Android Studio and clicking File->Open in Android Studio. Dragging the `./android` directory breaks as you describe, pressing File->Open works as expected (without the error you describe)

**Comment by ephemer** [comment]
This isn't really an issue we can do anything about. If someone comes across this and the instructions above aren't enough to fix it let us know.

**Comment by colemancda** [comment]
I have seen this too, but its really an Android studio bug, and it happens when using https://github.com/SwiftJava/android_toolchain (independently of this project).

**Comment by KrinalPatel11** [comment]
I go to build.gradle and click sync now. Then it worked.

Update :

File -> Sync Project with Gradle Files (Android Studio 3.1.1)

Tools -> Android -> Sync Project with Gradle Files (Android Studio 3.0.1)

Full Ans At [Here](https://icetutor.com/question/how-do-i-select-android-sdk-in-android-studio/)
