### ISSUE TITLE
Getting a minimalistic build with just SDL2

### ISSUE THREAD

**Issue by seivan** [flowkey/UIKit-cross-platform#264]
## Motivation 
It would be nice to get a small minimalistic boilerplate of a project that runs the Swift SDL2 bindings alone. I like where this project is going, but I see value even in the ability of setting up events and graphics across platforms. 

## Proposed solution
Maybe look into a fork of this repo with the `UIKit` stuff stripped out, and more focus on getting a Windows/Scene setup, with text and a coloured square. Another alternative is a demo/sample for https://github.com/flowkey/SDL2-SwiftPackageManager

## Potential alternatives
Another alternative would be to use something like https://github.com/SwiftGFX/SwiftBGFX instead for the underlying rendering. But I am not sure what issues there would be. It looks like your SDL2 repo is up to date, and those Swift bindings aren't.

**Comment by ephemer** [comment]
Hi @seivan, thanks for adding this issue.

That isn't really a goal of this project but we have also needed that functionality internally so it's possible we'll make https://github.com/flowkey/SDL2-SwiftPackageManager easier to get running standalone eventually.

Do you have experience with something like this? Would you be willing to put together a minimal PR in the SDL repo to get something along those lines working?

**Comment by seivan** [comment]
@ephemer Hey, thanks for getting back. I've decided to abandon Swift for now. But this is impressive none the less.

**Comment by ephemer** [comment]
@seivan best of luck with your project!
