### ISSUE TITLE
Couldn't find swift 4.1.3

### ISSUE THREAD

**Issue by JosmerDelgado** [flowkey/UIKit-cross-platform#280]
## Current behavior
when I try to build the app
Error:could not find the `swiftc` at expected path /Users/*****/Documents/Proyectos/Swift/Misterio2/MisterioHelper/UIKit/swift-android-toolchain/usr/bin/swiftc

## Expected behavior
must build correctly

**Comment by michaelknoch** [comment]
have you correctly installed your git submodules?
```git submodule update --init --recursive UIKit```
@JosmerDelgado

**Comment by ephemer** [comment]
@JosmerDelgado can you provide more details. If you’re on Mac, do you have Xcode installed and accepted the licence agreement?

**Comment by JosmerDelgado** [comment]
I have mac, I follow the steps :
" This project includes a DemoApp which runs on iOS, Android and Mac.

How to run it on different platforms:

Clone this project, cd into it and run git submodule update --init --recursive
Open ./samples/getting-started/DemoApp.xcodeproj in Xcode
Run DemoApp target for the iOS App
Run DemoAppMac target for the Mac App
Open ./samples/getting-started/android with Android Studio (install Android SDKs if necessary)
Connect an Android device and press "Run" for the Android App "

step by step.

**Comment by JosmerDelgado** [comment]
Yes I did 

> have you correctly installed your git submodules?
git submodule update --init --recursive UIKit

>

**Comment by JosmerDelgado** [comment]
I try to run the app from Android studio and show me this error: 

> Error:could not find the swiftc at expected path /Users/*****/Documents/Proyectos/Swift/Misterio2/MisterioHelper/UIKit/swift-android-toolchain/usr/bin/swiftc

**Comment by ephemer** [comment]
Ok, can you try going into the directory listed ending in swift-android-toolchain/ and running the setup.sh that’s in there from the command line? It should always be run automatically but maybe there’s an error being hidden by android studio

**Comment by JosmerDelgado** [comment]
When I run setup.sh show me this error. But i Already have installed swift
> [swift-android-toolchain] Couldn't find swift 4.1.3
[swift-android-toolchain] Download and install it from https://swift.org/download
[swift-android-toolchain] e.g. for macOS: https://swift.org/builds/swift-4.1.3-release/xcode/swift-4.1.3-RELEASE/swift-4.1.3-RELEASE-osx.pkg
[swift-android-toolchain] If you have the toolchain installed at a non-standard path (e.g. on Linux), 'export HOST_SWIFT_BIN_PATH=your/path/usr/bin' and try again

**Comment by ephemer** [comment]
Thanks, we may need to update the docs on this point: we need you to download that specific version of the Swift toolchain to be compatible with the version of Swift we use on Android. Just download and run the file linked next to "e.g. for macOS" and try to build in Android Studio again. The version shipped with Xcode isn't enough- you need that exact version.
