### ISSUE TITLE
Slack invite expired

### ISSUE THREAD

**Issue by advatar** [flowkey/UIKit-cross-platform#294]
## Current behavior

"This invite link is no longer active."

## Expected behavior

To get invited to Slack channel

## Steps to reproduce
1.
2.

## Environment
- Device:
- OS:
- UIKit Version:

**Comment by cshg** [comment]
thanks for raising this @advatar 
we are currently migrating to [Spectrum](https://spectrum.chat). Will post a link here and update the README soon.

**Comment by ephemer** [comment]
@cshg any progress on this?

**Comment by cshg** [comment]
@ephemer yes, I've updated the link to Spectrum in the main README: https://github.com/flowkey/UIKit-cross-platform#how-to-contribute
Closing this now :)

**Comment by ephemer** [comment]
💪 thanks @cshg !
