### ISSUE TITLE
Support SpriteKit?

### ISSUE THREAD

**Issue by ngocdaothanh** [flowkey/UIKit-cross-platform#295]
Is SpriteKit supported?
If not yet, can you outline how to port SpriteKit?

I guess SpriteKit is much simpler than UIKit.
So if UIKit can be ported, then SpriteKit can be ported too?

**Comment by ephemer** [comment]
Hi @ngocdaothanh thanks for your interest in the project! We don't have plans to port SpriteKit because we don't use it ourselves. It would be a great project though, let us know if you make any progress with it!

I am going to close this issue but feel free to update it if you have any news :)
