### ISSUE TITLE
a open source version of SwiftUI looks promising

### ISSUE THREAD

**Issue by mko-io** [flowkey/UIKit-cross-platform#298]
## Motivation 
[OpenSwiftUI](https://github.com/Cosmo/OpenSwiftUI) is a new open source implementation of SwiftUI, but it doesn't aim Android particularly. So I think UIKit-Cross could benefit from their effort.

## Proposed solution
share a same modern rendering backend like [bgfx](https://github.com/bkaradzic/bgfx) which support vulkan, metal and directX12

## Potential alternatives
there is a [proposal](https://github.com/Cosmo/OpenSwiftUI/issues/1) to use skia backend

**Comment by ephemer** [comment]
Thanks for posting. In the interests of keeping our Issue list actionable I'm going to close this, but we'd welcome any collaboration and exchange of ideas :)
