### ISSUE TITLE
`insertSubview:at:` seems to be off by one

### ISSUE THREAD

**Issue by janek** [flowkey/UIKit-cross-platform#308]
## Problem
`insertSubviews` seems to be off by one, running the same code on iOS and macOS gives a different view hierarchy. Code to reproduce this in our _DemoApp_ is attached at the bottom of the post, shortened pseudode below.

#### Pseudocode:
``` 
add 3 square views 
insert a blue horizontal view at index #1
``` 

#### Results:

|   iOS    |  macOS    |
|:-----|:----:|
|   <img width="981" alt="Screenshot 2020-02-18 at 14 23 16" src="https://user-images.githubusercontent.com/2146927/74752983-c1883c80-526f-11ea-9dfd-ab50bd03ad4b.png">   |   <img width="708" alt="Screenshot 2020-02-18 at 14 41 18" src="https://user-images.githubusercontent.com/2146927/74752990-c4832d00-526f-11ea-8b4a-0c6e4fa619ca.png">   | 
| Correct, blue view seems to be on the position with index 1 | Incorrect, blue view seems to be on position with index 2 | 

Note: this does not affect inserting at index 0 - that one behaves correctly 

## Snippets for reproduction and debugging
[DemoAppControllerForInsertSubviewsTesting.txt](https://github.com/flowkey/UIKit-cross-platform/files/4220332/DemoAppControllerForInsertSubviewsTesting.txt)
[testScrollIndicatorsHierarchyPosition.txt](https://github.com/flowkey/UIKit-cross-platform/files/4220337/testScrollIndicatorsHierarchyPosition.txt)

**Comment by ephemer** [comment]
@janek thanks for reporting this. Apparently this doesn't affect our use cases directly but it's a pretty fundamental functionality that we should get right. It should also be easy to make a unit test for this that runs on both iOS and Android for this.

**Comment by janek** [comment]
Yup, I already experimented with that. The snippet I posted doesn't exactly work, but is a useful starting point. It needs to have the indicator stuff commented out and have some more variety in cases it tests. 

I didn't want to get too sidetracked, as I was doing something else, but I'm very happy to push this quite soon.
