### ISSUE TITLE
if view.superview != nil { view.removeFromSuperview() }

### ISSUE THREAD

**Issue by chenyunguiMilook** [flowkey/UIKit-cross-platform#314]
https://github.com/flowkey/UIKit-cross-platform/blob/0e44ce485bf0e85fc161e1427970760dc2ff951e/Sources/UIView.swift#L211
should be if view.superview != nil { view.removeFromSuperview() } ?

**Comment by ephemer** [comment]
Thanks that looks correct. Could you make a pull request for this and add a test?

**Comment by chenyunguiMilook** [comment]
No problem!

**Comment by ephemer** [comment]
Thanks, @chenyunguiMilook!

**Comment by michaelknoch** [comment]
closing this because https://github.com/flowkey/UIKit-cross-platform/commit/196ab113ab457a2c393689317b9fe6c067c75fd7 was merged. Thanks @chenyunguiMilook
