### ISSUE TITLE
UINavigationController does not call `viewWillAppear`

### ISSUE THREAD

**Issue by OmerFlame** [flowkey/UIKit-cross-platform#341]
## Current behavior
When using a UINavigationController as the root view controller, you can see the Android-style navigation bar at the top but the content is completely black and doesn't seem to show the root view controller that I set inside the UINavigationController.

## Expected behavior
Seeing a normal UINavigationController but with the root view controller actually being shown instead of having a completely black screen below the navigation bar.

## Steps to reproduce
1. Use the sample project and set the root view controller of the window inside AppDelegate.swift to a UINavigationController that has ViewController as its root view controller.
2. Run it on any supported OS (got the same weird results with Android, macOS Monterey and iOS 15.1).

## Screenshots

![Screen Shot 2021-11-07 at 18 39 49](https://user-images.githubusercontent.com/17903236/140653740-5e8af258-b7e8-4f0a-8f3c-1a0ee21e4478.png)

## Environment
- Device: Xiaomi A2
- OS: Android Q
- UIKit Version: Latest commit (f8cb41875a3d7a6fa726170e48c68cf0498bd5ac)

**Comment by ephemer** [comment]
Thanks for the bug report @OmerFlame. We will have a look in the coming days

**Comment by ephemer** [comment]
Before I look into this too much - isn't this expected behaviour? 

Here the navigation controller would have no view to render, meaning the content of the content view will be transparent and fall through to the "abyss" behind it (which is black by default).

Put differently, what does a "normal" navigation controller that's empty look like? Are you expecting a white background instead?

**Comment by ephemer** [comment]
@OmerFlame I found the issue and made a fix for it in #343. With that patch, wrapping the demo app's ViewController in a UINavigationController works as expected

**Comment by ephemer** [comment]
@OmerFlame I merged a fix for this. Please let me know if you have any further feedback or questions
