### ISSUE TITLE
It does not support SwiftUI yet, right?

### ISSUE THREAD

**Issue by gzqyl** [flowkey/UIKit-cross-platform#391]
error: no such module 'SwiftUI'
import SwiftUI
       ^
ninja: build stopped: subcommand failed.

How to convert SwiftUI? UIKit works fine, while my project is written by SwiftUI.

**Comment by ephemer** [comment]
Hi @gzqyl, thanks for your interest in the project!

SwiftUI is not supported at this time. It's an interesting direction for us but we don't have the engineering resources to invest into that API currently.
